name: agos
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  firebase_database: ^11.3.7
  flutter_riverpod: ^2.6.1
  badges: ^3.1.2
  cloud_firestore: ^5.6.9
  google_fonts: ^6.2.1
  flutter_map: ^7.0.0
  flutter_map_heatmap: ^0.0.8
  latlong2: 0.9.1
  flutter_map_cancellable_tile_provider: ^3.0.2
  http: ^1.4.0
  intl: ^0.20.2
  url_launcher: ^6.3.2
  fl_chart: ^1.0.0
  geolocator: ^14.0.2
  mobile_scanner: ^5.1.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
