// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVtqDT-qoLscm_SIozlrYwpO87KdWdUZI',
    appId: '1:1075675221951:web:7d49ce764970065ac45b0a',
    messagingSenderId: '1075675221951',
    projectId: 'p2a-hackathon',
    authDomain: 'p2a-hackathon.firebaseapp.com',
    databaseURL:
        'https://p2a-hackathon-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'p2a-hackathon.firebasestorage.app',
    measurementId: 'G-BKLMC9QYXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJnfUWKcAVQIQBRs3_41aA8jz6JqlPmPA',
    appId: '1:1075675221951:android:6105bb108a4e6c1ec45b0a',
    messagingSenderId: '1075675221951',
    projectId: 'p2a-hackathon',
    databaseURL:
        'https://p2a-hackathon-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'p2a-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxhvXHXuV_ZPGdhJuJa59wZX_Z-WaadeU',
    appId: '1:1075675221951:ios:0dfcc411389fe77ac45b0a',
    messagingSenderId: '1075675221951',
    projectId: 'p2a-hackathon',
    databaseURL:
        'https://p2a-hackathon-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'p2a-hackathon.firebasestorage.app',
    iosBundleId: 'io.agos.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxhvXHXuV_ZPGdhJuJa59wZX_Z-WaadeU',
    appId: '1:1075675221951:ios:0dfcc411389fe77ac45b0a',
    messagingSenderId: '1075675221951',
    projectId: 'p2a-hackathon',
    databaseURL:
        'https://p2a-hackathon-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'p2a-hackathon.firebasestorage.app',
    iosBundleId: 'io.agos.app',
  );
}
